package com.scalefocus.bookstore.configs;

import org.springframework.context.annotation.Configuration;

@Configuration
public class AppConfig {
//TODO: REPLACE DB PROPERTIES NAMES IN THE APP WITH T_
//TODO: REFACTOR DDL (DATA DEFINITION LANGUAGE) SCRIPT TO MATCH THE UPDATED NAMES OF THE COLUMNS
//TODO: DROP BOOKS TABLE
//TODO: DROP AUTHORS TABLE
//TODO: START SB APPLICATION	
//TODO: EXECUTE SELECT FROM BOOKS; AND VERIFY IF THE SCHEMA MATCHES THE DTO
//TODO: EXECUTE SELECT FROM AUTHORS; AND VERIFY IF THE SCHEMA MATCHES THE DTO
//TODO: EXECUTE THE INSERT STATEMENTS FROM DML (DATA MANIPULATION LANGUAGE).	
}
